
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.webapp.replicas }}
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      {{- include "webappImage" . | indent 6}}      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fleetman-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: {{ .Values.webapp.nodePort }}

  type: NodePort
