apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: dheerajlearningdocker/demo:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    job: py-api
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: web
    port: 5000
    targetPort: 5000